services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'quiniblockDB'
      MYSQL_USER: 'fiveblocks'
      MYSQL_PASSWORD: 'password.24!'
      MYSQL_ROOT_PASSWORD: 'password.24!'
    ports:
      - '33066:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ../backend/script/quiniblockDB.sql:/docker-entrypoint-initdb.d/quiniblockDB.sql
    expose:
      - '3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'password.24!'
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  my-db:
